// Generated by https://quicktype.io

import { User } from '../auth/types';

export interface Post {
  title: string;
  body: string;
  url_slug: string;
  user: User;
  short_description: null;
  thumbnail: null;
  id: number;
  created_at: string;
  updated_at: string;
}
