// Generated by https://quicktype.io

import { User } from '../auth/types';

export interface Post {
  id: number;
  title: string;
  body: string;
  short_description: string | null;
  thumbnail: string | null;
  url_slug: string;
  user: User;
  created_at: string;
  updated_at: string;
}
